version: '3'
services:
  influxdb:
    build: influxdb/.
    networks:
      tik_net:
    volumes:
      - /home/pi/var/log/influxdb:/var/log/influxdb
      - /home/pi/var/lib/influxdb:/var/lib/influxdb
  telegraf:
    build: telegraf/.
    networks:
      tik_net:
    volumes:
      - /home/pi/var/log/telegraf:/var/log/telegraf
      - /home/pi/var/lib/telegraf:/var/lib/telegraf
  kapacitor:
    build: kapacitor/.
    networks:
      tik_net:
    volumes:
      - /home/pi/var/log/kapacitor:/var/log/kapacitor
      - /home/pi/var/lib/kapacitor:/var/lib/kapacitor
  chronograf:
    build: chronograf/. 
    networks:
      tik_net:
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "127.0.0.1:8888:8888"
    volumes:
      - /home/pi/var/log/chronograf:/var/log/chronograf
      - /home/pi/var/lib/chronograf:/var/lib/chronograf
  mosquitto:
    image: "eclipse-mosquitto:latest"
    networks:
      tik_net:
    ports:
      - "10.1.1.1:1883:1883"
networks:
  tik_net:
    driver: bridge
